In [2]:
#1 - Lista
#Lista é uma sequência ordenada de valores. Semelhante a uma matriz unidimensional em C
myfirstlist = [3,45,67,1234] 
myfirstlist

[3, 45, 67, 1234]

In [3]:
type(myfirstlist)

list

In [4]:
l2 = ["hello", 3, -100, False] #Pode armazenar todos os tipos de tipos de informação: inteira, real, string, booleana...
l2

['hello', 3, -100, False]

In [5]:
l3 = ["how are you", 55, myfirstlist] #Amazena, inclusive, até outras listas dentro ela
l3

['how are you', 55, [3, 45, 67, 1234]]

In [6]:
range(10)

range(0, 10)

In [7]:
list(range(10)) #list é usada pra criar listas

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
x = [0,1,2,3,4,5,6,7,8,9]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
y = list(range(10))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
z = list(range(1,11))
z

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
z1 = list(range(0,11,2)) #para números pares
z1

[0, 2, 4, 6, 8, 10]

In [12]:
z2 = list(range(1,11,2)) #para números ímpares
z2

[1, 3, 5, 7, 9]

In [13]:
#Cada termo da lista possui um índice e pode cer acessado individualmente
w = ['a','b','c','d','e']
#     0   1   2   3   4
print(w[0])
print(w[1])
print(w[2])
print(w[3])
print(w[4])

a
b
c
d
e


In [14]:
len(w)

5

In [15]:
w

['a', 'b', 'c', 'd', 'e']

In [16]:
# 0    1    2    3    4
#-5   -4   -3   -2   -1

print(w[2])
print(w[-3])

c
c


In [17]:
#Cada item da lista pode ser alterado
print(w)
w[2] = 63
print(w)

['a', 'b', 'c', 'd', 'e']
['a', 'b', 63, 'd', 'e']


In [19]:
d = list(range(0,11,2))
d

[0, 2, 4, 6, 8, 10]

In [20]:
w[-1] = d
w
#Foi alterado o valor do item w[-1] para a lista d

['a', 'b', 63, 'd', [0, 2, 4, 6, 8, 10]]

In [21]:
w[4][-1] = list(range(10,-1, -1))
w #Foi alterado o último valor da lista d que está dentro da lista w

['a', 'b', 63, 'd', [0, 2, 4, 6, 8, [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]]]

---

In [23]:
#2 - Slicing
l1 = ['A','B','C','D','E','F','G','H','I','J']
l1

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [24]:
# A  B  C  D  E  F  G  H  I  J 
# 0  1  2  3  4  5  6  7  8  9

l1[2:] #Os três primeiros termos da lista são "cortados" e permanece os termos posteriores

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [25]:
l1[:7] #A lista é "cortada" a partir do item 7, permanecendo os 7 itens anteriores

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [26]:
#lista[primeiro termo inclusivo : ultimo termo exclusivo : intervalo]
l1[2:7]

['C', 'D', 'E', 'F', 'G']

In [27]:
l1[-8:7]

['C', 'D', 'E', 'F', 'G']

In [28]:
l1[-8:-3]

['C', 'D', 'E', 'F', 'G']

In [29]:
l1[2:9]

['C', 'D', 'E', 'F', 'G', 'H', 'I']

In [30]:
l1[2:9:2]

['C', 'E', 'G', 'I']

In [31]:
l1

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [32]:
print(l1)         #lista completa
print(l1[::2])    #cortada a cada 2
print(l1[::3])    #cortada a cada 3
print(l1[::-2])   #cortada a cada -2

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
['A', 'C', 'E', 'G', 'I']
['A', 'D', 'G', 'J']
['J', 'H', 'F', 'D', 'B']


In [33]:
name = 'Matheus'
print(name[0:3])
print(name[0::2])
print(name[-1:-7:2]) #não funciona
print(name[-1:-8:-2])

Mat
Mtes

setM


In [34]:
l1[6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [35]:
l1[6:1:-2]

['G', 'E', 'C']

---

In [36]:
#3 - Tuplas
#A tupla é semelhante a uma lista porém é imutável.
t1 = (345, 674, 934)
print(t1)
print(t1[0])
print(t1[1])
print(t1[2])

(345, 674, 934)
345
674
934


In [37]:
t1[1]=34 #TypeError: 'tuple' object does not support item assignment

TypeError: 'tuple' object does not support item assignment

---

In [38]:
#4 - Funções
#As funções nos ajudam a evitar a redundância no código. Você pode criar uma parte que pode ser repetida várias vezes
range(20,31) #range é uma função

range(20, 31)

In [39]:
l1 = list(range(20,31)) #list é uma função
l1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [40]:
print(l1) #print é uma função

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [41]:
len(l1) #len é uma função

11

In [42]:
type(l1) #type é uma função

list

In [43]:
max(l1) #mostra o valor máximo; max é uma função

30

In [44]:
min(l1) #mostra o valor mínimo; min é uma função

20

In [45]:
max(11,12345,1234,999)

12345

In [46]:
max(tuple(range(10,201)))

200

---

In [47]:
#5 - Packages

In [48]:
'''
A module is simply a file containing Python definitions, functions 
and statements. Putting code into modules is useful because of the 
ability to import the module functionality into your script or IPython
session.

A package is just a way of collecting relates modules together within
a single tree-like hierarchy. Very complex packages like NumPy or
ScyPy have hundreds of individual modules so putting them into a
directory-like structure keeps things organized and avoids name
collisions.
'''

'\nA module is simply a file containing Python definitions, functions \nand statements. Putting code into modules is useful because of the \nability to import the module functionality into your script or IPython\nsession.\n\nA package is just a way of collecting relates modules together within\na single tree-like hierarchy. Very complex packages like NumPy or\nScyPy have hundreds of individual modules so putting them into a\ndirectory-like structure keeps things organized and avoids name\ncollisions.\n'

In [49]:
#---- Etapas
# 1 - Encontre o package(optional)
# 2 - Instale
# 3 - Importe o package ou importe a função

#---- 1 - Encontre o package: O MELHOR LUGAR PARA ENCONTRAR PACKAGES É NO GITHUB
#---- 2 - Instale o package(WINDOWS): Anaconda Prompt > "conda install packagename" ou "pip install packagename"
#---- 3 - Importe(WINDOWS): 
#          Exemplo: import NOME_DO_PACKAGE ou from NOME_DO_PACOTE.MÓDULO import CLASSE


In [ ]:
import scrapy #importando o package

In [ ]:
from scrapy.crawler import CrawlerProcess #importando a classe de um módulo

In [ ]:
import numpy

---

In [58]:
#6 - Numpy e Arrays
#Array (arranjo) armazena dados de forma semelhante a uma lista, porém pode organizar de forma unidimensional ou bidimensional (matriz)
l = [23245, 27, 546, 215, -1234]
l

[23245, 27, 546, 215, -1234]

In [59]:
import numpy as np #package para computação científica

In [60]:
a = np.array(l) #transforma a lista l em array
a

array([23245,    27,   546,   215, -1234])

In [61]:
#Qual a diferença entre listas e arrays?
#1 - Um array não pode ter tipos diferentes de dados
b = np.array([12, 455, 63.3, True, 'abc'])
b #transformou tudo em string

array(['12', '455', '63.3', 'True', 'abc'], 
      dtype='<U32')

In [62]:
#2 - Python armazena métodos dentro desses objetos (listas)
print(l.pop()) #mostra o último valor dessa lista e o tira
print(l)

-1234
[23245, 27, 546, 215]


In [63]:
#3 - Para arrays, python possui muito mais funções (ÚTIL EM DATA SCIENCE)
a.mean() #retorna a média dos valores

4559.8000000000002

In [64]:
#Slicing Arrays

In [65]:
a

array([23245,    27,   546,   215, -1234])

In [66]:
l

[23245, 27, 546, 215]

In [69]:
larray=np.array(l)
larray

array([23245,    27,   546,   215])

In [70]:
larray[0:3]

array([23245,    27,   546])

In [71]:
larray[0:4:2]

array([23245,   546])

In [73]:
b = larray[2:4]
b

array([546, 215])

In [74]:
b[0]

546

In [75]:
b[:]=111
b

array([111, 111])

In [76]:
larray

array([23245,    27,   111,   111])

In [77]:
#Quando trabalhamos com uma array, podemos mudar seus elementos protegendo a memória do computador

In [79]:
c = larray.copy()
c

array([23245,    27,   111,   111])

In [80]:
#Você pode mudar os elementos de uma array sem mudar a array principal. Use .copy()

In [88]:
g = np.array([13,15,19,1356,653556])
g

array([    13,     15,     19,   1356, 653556])

In [89]:
y = g.copy()
h = g
h

array([    13,     15,     19,   1356, 653556])

In [90]:
f = h[1:4]
print(f)
f[:] = 111
f

[  15   19 1356]


array([111, 111, 111])

In [92]:
print(g)
print(y)

[    13    111    111    111 653556]
[    13     15     19   1356 653556]
